# ~/.config/starship.toml

add_newline = false

prompt_order=[
  "directory",
  "git_branch",
  "git_status",
  "git_commit",
  "line_break",
  "character"
]

[git_branch]
symbol = ""

[git_commit]
only_detached = false

[hostname]
ssh_only = true

[package]
disabled = true

[character]
use_symbol_for_status = true  # Indicate error status by changing the symbol
